name: Docker

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: "${ secrets.DOCKER_REGISTRY }"
  DOCKER_REGISTRY_USER: "${{ secrets.DOCKER_REGISTRY_USER }}"
  DOCKER_REGISTRY_PASSWORD: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
  MM_NOTIFY_URL: "${{ secrets.MM_NOTIFY_URL }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and push image to ACR EE
        run: |
          docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
          # docker pull
          cat trigger.txt |awk '{print "docker pull "$1} '
          cat trigger.txt |awk '{print "docker pull "$1} '| sh
  
          # docker tag
          cat trigger.txt |awk '{print "docker tag "$1 " " $2} '
          cat trigger.txt |awk '{print "docker tag "$1 " " $2} '| sh
          
          # docker push
          cat trigger.txt |awk '{print "docker push " $2} '
          cat trigger.txt |awk '{print "docker push " $2} '| sh
