name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.QCLOUDUSERNAME }}
          password: ${{ secrets.QCLOUDPASSWORD }}

      - name: Build and push image to registry
        run: |
          # docker pull
          cat trigger.txt | awk '{print "docker pull "$2}'
          cat trigger.txt | awk '{print "docker pull "$2}' | sh

          # docker tag
          cat trigger.txt | awk '{print "docker tag "$2 " " $1}'
          cat trigger.txt | awk '{print "docker tag "$2 " " $1}' | sh

          # docker push
          cat trigger.txt | awk '{print "docker push " $1}'
          cat trigger.txt | awk '{print "docker push " $1}' | sh
