name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    steps:
      # 设置 Docker buildx 工具
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # 检出代码
      - name: Check out code
        uses: actions/checkout@v2

      # 登录到腾讯云容器镜像仓库
      - name: Login to Tencent Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.QCLOUDUSERNAME }}
          password: ${{ secrets.QCLOUDPASSWORD }}

      # 构建并推送镜像到仓库
      - name: Build and push image to registry
        run: |
          while read -r target_image source_image; do
            echo "处理镜像 $target_image 从 $source_image"

            # 拉取源镜像
            docker pull $source_image
            # 标记源镜像为目标镜像
            docker tag $source_image $target_image
            # 推送目标镜像到仓库
            docker push $target_image

          done < trigger.txt
